### ISSUE TITLE
Is there any pre-built trivial tokenizer with space delimiter  for training Roberta ?

### ISSUE THREAD

**Issue by venkateshvayyavuru** [huggingface/tokenizers#640]
Hi,
  I have corpus of Telugu language of 2M word tokens and vocabulary size of 5000.  I need to use these tokens as it is for training the masked language model. I mean tokenization with space delimiter. 
   1. Is there any pre-built trivial tokenizer ?
   2.Is it possible to use trivial tokenizer for training Roberta ?

Thanks in advance,
Venkatesh Vayyavuru.

**Comment by iliaschalkidis** [comment]
Hi, 

I have the very same question. It's really unclear how can we train a new RobertaTokenizer, i.e., new vocabulary, in order to then re-use it and train a new ROBERTA, or XLM-R model with the transformers library, i.e., `run_mlm.py`.

On the other hand, the same process for BERT is crystal clear 😄

**Comment by david-waterworth** [comment]
I don't believe there is a built-in end to end Robert tokeniser, but it is pretty easy to create one using the Bert implementation as a template (https://github.com/huggingface/tokenizers/tree/master/bindings/python/py_src/tokenizers/implementations) but use the `RobertaProcessing` class as the post processor.

Once you have a tokenizer.json file you can then load this directly using AutoTokenizer.from_pretrained()

You could even use the Bert tokeniser, save the tokenizer.json file then hand edit the json to switch the post_processor (you can probably also create and train a BertTokenizer but replace the post_processor class before serialising but I've not tried this.

>   "post_processor": {
>     "type": "RobertaProcessing",
>     "sep": [
>       "</s>",
>       1
>     ],
>     "cls": [
>       "<s>",
>       0
>     ],
>     "trim_offsets": true,
>     "add_prefix_space": true
>   },

**Comment by iliaschalkidis** [comment]
Hi @david-waterworth,

I didn't knew, there are still pre-baked `implementations` in the current version, soand I started building a pipelined tokenizer from scratch, thanks for this!

I think it's a good idea to stick to:

 ```python
 from tokenizers import trainers, processors, implementations
tokenizer = implementations.SentencePieceBPETokenizer()
tokenizer.post_processor = processors.RobertaProcessing()
```

In order to be aligned with the original Facebook `RobertaTokenizer` trained with `SentencePiece` instead of `WordPiece`... I mean if there is any difference at all. After all, I am not an expert with all these tokenization algos 🤦

**Comment by david-waterworth** [comment]
This works for me, you need to pass the string and index of the sep token to RobertaProcessing, also the tokeniser should be saved as `tokenizer.json`, I think saving as vocab.json confused the loader - older versions of `tokenizers` appear to have saved out the model (i.e. merges.txt, vocab.json etc) but the new one serialises everything into one file (tokenizer.json).

```
from tokenizers import trainers, processors, implementations

special_tokens = ['<pad>', '<unk>', '<mask>', "<s>", "</s>"]
tokenizer = implementations.SentencePieceBPETokenizer()
tokenizer.post_processor = tokenizers.processors.RobertaProcessing(
    sep=("</s>",special_tokens.index("</s>")), 
    cls=("<s>",special_tokens.index("<s>"))
    )

tokenizer.train(files=glob.glob(f'{DATA_PATH}/*.txt'), special_tokens=special_tokens)
tokenizer.save(f'{TOKENIZER_PATH}/tokenizer.json')
```

```
from transformers import RobertaTokenizerFast
roberta_tokenizer = RobertaTokenizerFast.from_pretrained(f'{TOKENIZER_PATH}')
print(roberta_tokenizer('This is a holly cow'))
```

Finally, in order to use `AutoTokenizer` rather than `RobertaTokenizerFast` you need to create a `config.json` in {TOKENIZER_PATH}. 

> {
>     "unk_token": "<unk>",
>     "bos_token": "<s>",
>     "eos_token": "</s>",
>     "add_prefix_space": true,
>     "errors": "replace",
>     "sep_token": "</s>",
>     "cls_token": "<s>",
>     "pad_token": "<pad>",
>     "mask_token": "<mask>",
>     "special_tokens_map_file": null,
>     "name_or_path": f"{TOKENIZER_PATH}"
> }

**Comment by iliaschalkidis** [comment]
Hi @david-waterworth, thanks for that.

The current error, copy-pasting the last proposed code is now:

```
Traceback (most recent call last):
  File "/Users/kiddothe2b/PycharmProjects/multi-eurlex/pre-training/train_tokenizer.py", line 26, in <module>
    roberta_tokenizer = RobertaTokenizerFast.from_pretrained(f'{TOKENIZER_PATH}')
  File "/Users/kiddothe2b/anaconda3/envs/TF2/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1789, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "/Users/kiddothe2b/anaconda3/envs/TF2/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1860, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/kiddothe2b/anaconda3/envs/TF2/lib/python3.7/site-packages/transformers/models/roberta/tokenization_roberta_fast.py", line 173, in __init__
    **kwargs,
  File "/Users/kiddothe2b/anaconda3/envs/TF2/lib/python3.7/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 148, in __init__
    self.backend_tokenizer.pre_tokenizer = pre_tok_class(**pre_tok_state)
TypeError: PyMetaspace.__new__() got an unexpected keyword argument: str_rep
```

That's me working on `tokenizer==0.10.1`  and `transformers==4.3.3`

I am able to use the `AutoTokenizer`, even when the `config.json` does not include the final line (`"name_or_path"`).

I am just curious if this solution will pair well with training a new `RobertaForMaskedLM` with the transformers' `train_mlm.py` script...

**Comment by david-waterworth** [comment]
I slightly modified train_mlm.py for my own purposes but it works well for me. The exception you're seeing looks the same as https://github.com/huggingface/transformers/issues/10448 - it may be you have a mismatch between the tokenizer and transformers version, or there's a bug in the library? I'm using `tokenizers==0.9.4` and `transformers==4.0.1`

**Comment by david-waterworth** [comment]
Also I just found out you need "model_type": "roberta" in the config.json, otherwise it thinks it's a BERT tokeniser and adds [UNK],[SEP] etc.

**Comment by venkateshvayyavuru** [comment]
Thanks @david-waterworth  and @iliaschalkidis.  It worked for me.

**Comment by n1t0** [comment]
The tokenizer for Roberta is based on a byte-level BPE. If you want to build exactly the same tokenizer, that can be used as a drop-in replacement for `RobertaTokenizer` in `transformers`, you can do the following:
```python
from tokenizers import Tokenizer, models, pre_tokenizers, trainers

BOS = "<s>"
EOS = "</s>"
UNK = "<unk>"
PAD = "<pad>"
MASK = "<mask>"

tokenizer = Tokenizer(models.BPE())
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=False)
tokenizer.decoder = decoders.ByteLevel()

# Set the training hyperparameters
trainer = trainers.BpeTrainer(
    vocab_size=50000,
    special_tokens=[BOS, PAD, EOS, UNK, MASK],
    initial_alphabet=pre_tokenizers.ByteLevel.alphabet()
)

# Train it with either files or an iterator:
tokenizer.train(files, trainer=trainer)
# OR
tokenizer.train_from_iterator(content, trainer=trainer)

# Attach the Roberta Processing
tokenizer.post_processor = processors.RobertaProcessing(
    sep=(EOS, tokenizer.token_to_id(EOS)),
    cls=(BOS, tokenizer.token_to_id(BOS))
)

# And save it:
tokenizer.save("tokenizer.json")

# Load with transformers
from transformers import RobertaTokenizerFast
tok = RobertaTokenizerFast(tokenizer_file="tokenizer.json")
```
